[2025-08-02T01:47:36.957+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=cdr_pipeline/run_id=manual__2025-08-02T01:20:57.581723+00:00/task_id=load_to_redshift permission to 509
[2025-08-02T01:47:37.102+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=cdr_pipeline/run_id=manual__2025-08-02T01:20:57.581723+00:00/task_id=load_to_redshift permission to 509
[2025-08-02T01:47:37.207+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cdr_pipeline.load_to_redshift manual__2025-08-02T01:20:57.581723+00:00 [queued]>
[2025-08-02T01:47:37.228+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cdr_pipeline.load_to_redshift manual__2025-08-02T01:20:57.581723+00:00 [queued]>
[2025-08-02T01:47:37.229+0000] {taskinstance.py:2170} INFO - Starting attempt 7 of 7
[2025-08-02T01:47:37.270+0000] {taskinstance.py:2191} INFO - Executing <Task(S3ToRedshiftOperator): load_to_redshift> on 2025-08-02 01:20:57.581723+00:00
[2025-08-02T01:47:37.285+0000] {standard_task_runner.py:60} INFO - Started process 1511 to run task
[2025-08-02T01:47:37.293+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'cdr_pipeline', 'load_to_redshift', 'manual__2025-08-02T01:20:57.581723+00:00', '--job-id', '95', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpog61nyx1']
[2025-08-02T01:47:37.296+0000] {standard_task_runner.py:88} INFO - Job 95: Subtask load_to_redshift
[2025-08-02T01:47:37.409+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=cdr_pipeline/run_id=manual__2025-08-02T01:20:57.581723+00:00/task_id=load_to_redshift permission to 509
[2025-08-02T01:47:37.428+0000] {task_command.py:423} INFO - Running <TaskInstance: cdr_pipeline.load_to_redshift manual__2025-08-02T01:20:57.581723+00:00 [running]> on host f2527419f673
[2025-08-02T01:47:37.640+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cdr_pipeline' AIRFLOW_CTX_TASK_ID='load_to_redshift' AIRFLOW_CTX_EXECUTION_DATE='2025-08-02T01:20:57.581723+00:00' AIRFLOW_CTX_TRY_NUMBER='7' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-02T01:20:57.581723+00:00'
[2025-08-02T01:47:37.663+0000] {base.py:83} INFO - Using connection ID 'aws_default' for task execution.
[2025-08-02T01:47:37.678+0000] {base.py:83} INFO - Using connection ID 'aws_default' for task execution.
[2025-08-02T01:47:37.679+0000] {connection_wrapper.py:378} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2025-08-02T01:47:37.699+0000] {s3_to_redshift.py:192} INFO - Executing COPY command...
[2025-08-02T01:47:37.713+0000] {base.py:83} INFO - Using connection ID 'redshift_default' for task execution.
[2025-08-02T01:47:37.718+0000] {connection_wrapper.py:378} INFO - AWS Connection (conn_id='redshift_default', conn_type='aws') credentials retrieved from login and password.
[2025-08-02T01:47:37.719+0000] {warnings.py:109} WARNING - <string>:9: AirflowProviderDeprecationWarning: Host tf-redshift-cluster.ci896s3qzt6h.eu-west-1.redshift.amazonaws.com:5439/dev_db specified in the connection is not used. Please, set it on extra['endpoint_url'] instead

[2025-08-02T01:47:40.225+0000] {redshift_data.py:113} INFO - Polling statement b10356cf-ed7b-4b4f-ba87-4402ea835121
[2025-08-02T01:47:40.433+0000] {redshift_data.py:129} INFO - Query STARTED
[2025-08-02T01:47:50.442+0000] {redshift_data.py:113} INFO - Polling statement b10356cf-ed7b-4b4f-ba87-4402ea835121
[2025-08-02T01:47:50.672+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/transfers/s3_to_redshift.py", line 194, in execute
    redshift_hook.execute_query(sql=sql, **self.redshift_data_api_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/redshift_data.py", line 107, in execute_query
    self.wait_for_results(statement_id, poll_interval=poll_interval)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/redshift_data.py", line 124, in wait_for_results
    raise ValueError(
ValueError: Statement 'b10356cf-ed7b-4b4f-ba87-4402ea835121' terminated with status FAILED. Response details: {'ClusterIdentifier': 'tf-redshift-cluster',
 'CreatedAt': datetime.datetime(2025, 8, 2, 1, 47, 40, 19000, tzinfo=tzlocal()),
 'Database': 'dev_db',
 'DbUser': 'masterdb',
 'Duration': -1,
 'Error': 'ERROR: conflicting or redundant options',
 'HasResultSet': False,
 'Id': 'b10356cf-ed7b-4b4f-ba87-4402ea835121',
 'QueryString': '\n'
                '                    COPY public.cdr_records \n'
                '                    FROM '
                "'s3://cdr-faker-data-dfad0cb7/cdr_2025-08-02.parquet'\n"
                '                    credentials\n'
                "                    ''\n"
                '                    \n'
                '                    FORMAT AS PARQUET\n'
                "\t\t\tIAM_ROLE '';\n"
                '        ',
 'RedshiftPid': 1073840389,
 'RedshiftQueryId': -1,
 'ResponseMetadata': {'HTTPHeaders': {'content-length': '679',
                                      'content-type': 'application/x-amz-json-1.1',
                                      'date': 'Sat, 02 Aug 2025 01:47:50 GMT',
                                      'x-amzn-requestid': '550f0518-f7c8-40b5-9a60-85dc52bbb9ad'},
                      'HTTPStatusCode': 200,
                      'RequestId': '550f0518-f7c8-40b5-9a60-85dc52bbb9ad',
                      'RetryAttempts': 0},
 'ResultRows': -1,
 'ResultSize': -1,
 'Status': 'FAILED',
 'UpdatedAt': datetime.datetime(2025, 8, 2, 1, 47, 40, 441000, tzinfo=tzlocal())}
[2025-08-02T01:47:50.723+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=cdr_pipeline, task_id=load_to_redshift, execution_date=20250802T012057, start_date=20250802T014737, end_date=20250802T014750
[2025-08-02T01:47:50.753+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 95 for task load_to_redshift (Statement 'b10356cf-ed7b-4b4f-ba87-4402ea835121' terminated with status FAILED. Response details: {'ClusterIdentifier': 'tf-redshift-cluster',
 'CreatedAt': datetime.datetime(2025, 8, 2, 1, 47, 40, 19000, tzinfo=tzlocal()),
 'Database': 'dev_db',
 'DbUser': 'masterdb',
 'Duration': -1,
 'Error': 'ERROR: conflicting or redundant options',
 'HasResultSet': False,
 'Id': 'b10356cf-ed7b-4b4f-ba87-4402ea835121',
 'QueryString': '\n'
                '                    COPY public.cdr_records \n'
                '                    FROM '
                "'s3://cdr-faker-data-dfad0cb7/cdr_2025-08-02.parquet'\n"
                '                    credentials\n'
                "                    ''\n"
                '                    \n'
                '                    FORMAT AS PARQUET\n'
                "\t\t\tIAM_ROLE '';\n"
                '        ',
 'RedshiftPid': 1073840389,
 'RedshiftQueryId': -1,
 'ResponseMetadata': {'HTTPHeaders': {'content-length': '679',
                                      'content-type': 'application/x-amz-json-1.1',
                                      'date': 'Sat, 02 Aug 2025 01:47:50 GMT',
                                      'x-amzn-requestid': '550f0518-f7c8-40b5-9a60-85dc52bbb9ad'},
                      'HTTPStatusCode': 200,
                      'RequestId': '550f0518-f7c8-40b5-9a60-85dc52bbb9ad',
                      'RetryAttempts': 0},
 'ResultRows': -1,
 'ResultSize': -1,
 'Status': 'FAILED',
 'UpdatedAt': datetime.datetime(2025, 8, 2, 1, 47, 40, 441000, tzinfo=tzlocal())}; 1511)
[2025-08-02T01:47:50.798+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-08-02T01:47:50.824+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
