[2025-08-02T03:54:47.313+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=cdr_pipeline/run_id=manual__2025-08-02T03:41:43.683798+00:00/task_id=load_to_redshift permission to 509
[2025-08-02T03:54:47.391+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=cdr_pipeline/run_id=manual__2025-08-02T03:41:43.683798+00:00/task_id=load_to_redshift permission to 509
[2025-08-02T03:54:47.437+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cdr_pipeline.load_to_redshift manual__2025-08-02T03:41:43.683798+00:00 [queued]>
[2025-08-02T03:54:47.451+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cdr_pipeline.load_to_redshift manual__2025-08-02T03:41:43.683798+00:00 [queued]>
[2025-08-02T03:54:47.452+0000] {taskinstance.py:2170} INFO - Starting attempt 6 of 7
[2025-08-02T03:54:47.470+0000] {taskinstance.py:2191} INFO - Executing <Task(S3ToRedshiftOperator): load_to_redshift> on 2025-08-02 03:41:43.683798+00:00
[2025-08-02T03:54:47.484+0000] {standard_task_runner.py:60} INFO - Started process 3319 to run task
[2025-08-02T03:54:47.493+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'cdr_pipeline', 'load_to_redshift', 'manual__2025-08-02T03:41:43.683798+00:00', '--job-id', '139', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpzjtq1gs4']
[2025-08-02T03:54:47.496+0000] {standard_task_runner.py:88} INFO - Job 139: Subtask load_to_redshift
[2025-08-02T03:54:47.593+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=cdr_pipeline/run_id=manual__2025-08-02T03:41:43.683798+00:00/task_id=load_to_redshift permission to 509
[2025-08-02T03:54:47.612+0000] {task_command.py:423} INFO - Running <TaskInstance: cdr_pipeline.load_to_redshift manual__2025-08-02T03:41:43.683798+00:00 [running]> on host f2527419f673
[2025-08-02T03:54:47.783+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cdr_pipeline' AIRFLOW_CTX_TASK_ID='load_to_redshift' AIRFLOW_CTX_EXECUTION_DATE='2025-08-02T03:41:43.683798+00:00' AIRFLOW_CTX_TRY_NUMBER='6' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-02T03:41:43.683798+00:00'
[2025-08-02T03:54:47.798+0000] {base.py:83} INFO - Using connection ID 'aws_default' for task execution.
[2025-08-02T03:54:47.807+0000] {base.py:83} INFO - Using connection ID 'aws_default' for task execution.
[2025-08-02T03:54:47.809+0000] {connection_wrapper.py:378} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2025-08-02T03:54:47.824+0000] {s3_to_redshift.py:192} INFO - Executing COPY command...
[2025-08-02T03:54:47.834+0000] {base.py:83} INFO - Using connection ID 'redshift_default' for task execution.
[2025-08-02T03:54:47.835+0000] {connection_wrapper.py:378} INFO - AWS Connection (conn_id='redshift_default', conn_type='aws') credentials retrieved from login and password.
[2025-08-02T03:54:47.836+0000] {warnings.py:109} WARNING - <string>:9: AirflowProviderDeprecationWarning: Host tf-redshift-cluster.ci896s3qzt6h.eu-west-1.redshift.amazonaws.com:5439/dev_db specified in the connection is not used. Please, set it on extra['endpoint_url'] instead

[2025-08-02T03:54:49.464+0000] {redshift_data.py:113} INFO - Polling statement 6db7e951-f867-4de9-9362-cdedadd3464c
[2025-08-02T03:54:49.648+0000] {redshift_data.py:129} INFO - Query STARTED
[2025-08-02T03:55:00.824+0000] {redshift_data.py:113} INFO - Polling statement 6db7e951-f867-4de9-9362-cdedadd3464c
[2025-08-02T03:55:01.078+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/transfers/s3_to_redshift.py", line 194, in execute
    redshift_hook.execute_query(sql=sql, **self.redshift_data_api_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/redshift_data.py", line 107, in execute_query
    self.wait_for_results(statement_id, poll_interval=poll_interval)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/redshift_data.py", line 124, in wait_for_results
    raise ValueError(
ValueError: Statement '6db7e951-f867-4de9-9362-cdedadd3464c' terminated with status FAILED. Response details: {'ClusterIdentifier': 'tf-redshift-cluster',
 'CreatedAt': datetime.datetime(2025, 8, 2, 3, 54, 49, 693000, tzinfo=tzlocal()),
 'Database': 'dev_db',
 'DbUser': 'masterdb',
 'Duration': -1,
 'Error': 'ERROR: Spectrum Scan Error\n'
          '  Detail: \n'
          '  -----------------------------------------------\n'
          '  error:  Spectrum Scan Error\n'
          '  code:      15007\n'
          '  context:   File '
          "'https://s3.eu-west-1.amazonaws.com/cdr-faker-data-dfad0cb7/cdr_2025-08-02.parquet/66046c9b895e438284f3fd0425f0fef6.snappy.parquet' "
          'has an incompatible Parquet schema for column '
          "'s3://cdr-faker-data-dfad0cb7/cdr_2025-08-02.parquet/.call_start'. "
          'Column\n'
          '  query:     209572\n'
          '  location:  dory_util.cpp:1776\n'
          '  process:   worker_thread [pid=8920]\n'
          '  -----------------------------------------------\n',
 'HasResultSet': False,
 'Id': '6db7e951-f867-4de9-9362-cdedadd3464c',
 'QueryString': '\n'
                '                    COPY public.cdr_records \n'
                '                    FROM '
                "'s3://cdr-faker-data-dfad0cb7/cdr_2025-08-02.parquet/'\n"
                '                    credentials\n'
                "                    ''\n"
                '                    \n'
                '                    FORMAT AS PARQUET;\n'
                '        ',
 'RedshiftPid': 1073954960,
 'RedshiftQueryId': 209573,
 'ResponseMetadata': {'HTTPHeaders': {'content-length': '1183',
                                      'content-type': 'application/x-amz-json-1.1',
                                      'date': 'Sat, 02 Aug 2025 03:55:00 GMT',
                                      'x-amzn-requestid': 'fcdd09fb-341e-48e8-8b6b-33d2510c5c5d'},
                      'HTTPStatusCode': 200,
                      'RequestId': 'fcdd09fb-341e-48e8-8b6b-33d2510c5c5d',
                      'RetryAttempts': 0},
 'ResultRows': -1,
 'ResultSize': -1,
 'Status': 'FAILED',
 'UpdatedAt': datetime.datetime(2025, 8, 2, 3, 54, 50, 621000, tzinfo=tzlocal())}
[2025-08-02T03:55:01.113+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=cdr_pipeline, task_id=load_to_redshift, execution_date=20250802T034143, start_date=20250802T035447, end_date=20250802T035501
[2025-08-02T03:55:01.152+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 139 for task load_to_redshift (Statement '6db7e951-f867-4de9-9362-cdedadd3464c' terminated with status FAILED. Response details: {'ClusterIdentifier': 'tf-redshift-cluster',
 'CreatedAt': datetime.datetime(2025, 8, 2, 3, 54, 49, 693000, tzinfo=tzlocal()),
 'Database': 'dev_db',
 'DbUser': 'masterdb',
 'Duration': -1,
 'Error': 'ERROR: Spectrum Scan Error\n'
          '  Detail: \n'
          '  -----------------------------------------------\n'
          '  error:  Spectrum Scan Error\n'
          '  code:      15007\n'
          '  context:   File '
          "'https://s3.eu-west-1.amazonaws.com/cdr-faker-data-dfad0cb7/cdr_2025-08-02.parquet/66046c9b895e438284f3fd0425f0fef6.snappy.parquet' "
          'has an incompatible Parquet schema for column '
          "'s3://cdr-faker-data-dfad0cb7/cdr_2025-08-02.parquet/.call_start'. "
          'Column\n'
          '  query:     209572\n'
          '  location:  dory_util.cpp:1776\n'
          '  process:   worker_thread [pid=8920]\n'
          '  -----------------------------------------------\n',
 'HasResultSet': False,
 'Id': '6db7e951-f867-4de9-9362-cdedadd3464c',
 'QueryString': '\n'
                '                    COPY public.cdr_records \n'
                '                    FROM '
                "'s3://cdr-faker-data-dfad0cb7/cdr_2025-08-02.parquet/'\n"
                '                    credentials\n'
                "                    ''\n"
                '                    \n'
                '                    FORMAT AS PARQUET;\n'
                '        ',
 'RedshiftPid': 1073954960,
 'RedshiftQueryId': 209573,
 'ResponseMetadata': {'HTTPHeaders': {'content-length': '1183',
                                      'content-type': 'application/x-amz-json-1.1',
                                      'date': 'Sat, 02 Aug 2025 03:55:00 GMT',
                                      'x-amzn-requestid': 'fcdd09fb-341e-48e8-8b6b-33d2510c5c5d'},
                      'HTTPStatusCode': 200,
                      'RequestId': 'fcdd09fb-341e-48e8-8b6b-33d2510c5c5d',
                      'RetryAttempts': 0},
 'ResultRows': -1,
 'ResultSize': -1,
 'Status': 'FAILED',
 'UpdatedAt': datetime.datetime(2025, 8, 2, 3, 54, 50, 621000, tzinfo=tzlocal())}; 3319)
[2025-08-02T03:55:01.255+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-08-02T03:55:01.303+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
