[2025-08-02T04:07:08.017+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=cdr_pipeline/run_id=manual__2025-08-02T03:41:43.683798+00:00/task_id=load_to_redshift permission to 509
[2025-08-02T04:07:08.070+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=cdr_pipeline/run_id=manual__2025-08-02T03:41:43.683798+00:00/task_id=load_to_redshift permission to 509
[2025-08-02T04:07:08.114+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cdr_pipeline.load_to_redshift manual__2025-08-02T03:41:43.683798+00:00 [queued]>
[2025-08-02T04:07:08.128+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cdr_pipeline.load_to_redshift manual__2025-08-02T03:41:43.683798+00:00 [queued]>
[2025-08-02T04:07:08.129+0000] {taskinstance.py:2170} INFO - Starting attempt 9 of 9
[2025-08-02T04:07:08.150+0000] {taskinstance.py:2191} INFO - Executing <Task(S3ToRedshiftOperator): load_to_redshift> on 2025-08-02 03:41:43.683798+00:00
[2025-08-02T04:07:08.162+0000] {standard_task_runner.py:60} INFO - Started process 3498 to run task
[2025-08-02T04:07:08.170+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'cdr_pipeline', 'load_to_redshift', 'manual__2025-08-02T03:41:43.683798+00:00', '--job-id', '145', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpcmpv6fxl']
[2025-08-02T04:07:08.173+0000] {standard_task_runner.py:88} INFO - Job 145: Subtask load_to_redshift
[2025-08-02T04:07:08.260+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=cdr_pipeline/run_id=manual__2025-08-02T03:41:43.683798+00:00/task_id=load_to_redshift permission to 509
[2025-08-02T04:07:08.276+0000] {task_command.py:423} INFO - Running <TaskInstance: cdr_pipeline.load_to_redshift manual__2025-08-02T03:41:43.683798+00:00 [running]> on host f2527419f673
[2025-08-02T04:07:08.418+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cdr_pipeline' AIRFLOW_CTX_TASK_ID='load_to_redshift' AIRFLOW_CTX_EXECUTION_DATE='2025-08-02T03:41:43.683798+00:00' AIRFLOW_CTX_TRY_NUMBER='9' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-02T03:41:43.683798+00:00'
[2025-08-02T04:07:08.435+0000] {base.py:83} INFO - Using connection ID 'aws_default' for task execution.
[2025-08-02T04:07:08.447+0000] {base.py:83} INFO - Using connection ID 'aws_default' for task execution.
[2025-08-02T04:07:08.451+0000] {connection_wrapper.py:378} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2025-08-02T04:07:08.468+0000] {s3_to_redshift.py:192} INFO - Executing COPY command...
[2025-08-02T04:07:08.479+0000] {base.py:83} INFO - Using connection ID 'redshift_default' for task execution.
[2025-08-02T04:07:08.482+0000] {connection_wrapper.py:378} INFO - AWS Connection (conn_id='redshift_default', conn_type='aws') credentials retrieved from login and password.
[2025-08-02T04:07:08.483+0000] {warnings.py:109} WARNING - <string>:9: AirflowProviderDeprecationWarning: Host tf-redshift-cluster.ci896s3qzt6h.eu-west-1.redshift.amazonaws.com:5439/dev_db specified in the connection is not used. Please, set it on extra['endpoint_url'] instead

[2025-08-02T04:07:10.238+0000] {redshift_data.py:113} INFO - Polling statement 701b1514-9f49-4101-9736-61a1ca94bbff
[2025-08-02T04:07:10.431+0000] {redshift_data.py:129} INFO - Query STARTED
[2025-08-02T04:07:20.441+0000] {redshift_data.py:113} INFO - Polling statement 701b1514-9f49-4101-9736-61a1ca94bbff
[2025-08-02T04:07:20.648+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/transfers/s3_to_redshift.py", line 194, in execute
    redshift_hook.execute_query(sql=sql, **self.redshift_data_api_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/redshift_data.py", line 107, in execute_query
    self.wait_for_results(statement_id, poll_interval=poll_interval)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/redshift_data.py", line 124, in wait_for_results
    raise ValueError(
ValueError: Statement '701b1514-9f49-4101-9736-61a1ca94bbff' terminated with status FAILED. Response details: {'ClusterIdentifier': 'tf-redshift-cluster',
 'CreatedAt': datetime.datetime(2025, 8, 2, 4, 7, 10, 40000, tzinfo=tzlocal()),
 'Database': 'dev_db',
 'DbUser': 'masterdb',
 'Duration': -1,
 'Error': 'ERROR: Spectrum Scan Error\n'
          '  Detail: \n'
          '  -----------------------------------------------\n'
          '  error:  Spectrum Scan Error\n'
          '  code:      15007\n'
          '  context:   Unmatched number of columns between table and file. '
          'Table columns: 21, Data columns: 22, File name: '
          'https://s3.eu-west-1.amazonaws.com/cdr-faker-data-dfad0cb7/cdr_2025-08-02.parquet/d1de776ed6f747c688e0280773b470d5.snappy.parquet\n'
          '  query:     209850\n'
          '  location:  dory_util.cpp:1776\n'
          '  process:   worker_thread [pid=16259]\n'
          '  -----------------------------------------------\n',
 'HasResultSet': False,
 'Id': '701b1514-9f49-4101-9736-61a1ca94bbff',
 'QueryString': '\n'
                '                    COPY public.cdr_records \n'
                '                    FROM '
                "'s3://cdr-faker-data-dfad0cb7/cdr_2025-08-02.parquet/'\n"
                '                    credentials\n'
                "                    ''\n"
                '                    \n'
                '                    FORMAT AS PARQUET;\n'
                '        ',
 'RedshiftPid': 1073930392,
 'RedshiftQueryId': 209851,
 'ResponseMetadata': {'HTTPHeaders': {'content-length': '1156',
                                      'content-type': 'application/x-amz-json-1.1',
                                      'date': 'Sat, 02 Aug 2025 04:07:20 GMT',
                                      'x-amzn-requestid': 'a3dbd868-f4a1-4519-ae45-8d8569b665ef'},
                      'HTTPStatusCode': 200,
                      'RequestId': 'a3dbd868-f4a1-4519-ae45-8d8569b665ef',
                      'RetryAttempts': 0},
 'ResultRows': -1,
 'ResultSize': -1,
 'Status': 'FAILED',
 'UpdatedAt': datetime.datetime(2025, 8, 2, 4, 7, 10, 995000, tzinfo=tzlocal())}
[2025-08-02T04:07:20.681+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=cdr_pipeline, task_id=load_to_redshift, execution_date=20250802T034143, start_date=20250802T040708, end_date=20250802T040720
[2025-08-02T04:07:20.703+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 145 for task load_to_redshift (Statement '701b1514-9f49-4101-9736-61a1ca94bbff' terminated with status FAILED. Response details: {'ClusterIdentifier': 'tf-redshift-cluster',
 'CreatedAt': datetime.datetime(2025, 8, 2, 4, 7, 10, 40000, tzinfo=tzlocal()),
 'Database': 'dev_db',
 'DbUser': 'masterdb',
 'Duration': -1,
 'Error': 'ERROR: Spectrum Scan Error\n'
          '  Detail: \n'
          '  -----------------------------------------------\n'
          '  error:  Spectrum Scan Error\n'
          '  code:      15007\n'
          '  context:   Unmatched number of columns between table and file. '
          'Table columns: 21, Data columns: 22, File name: '
          'https://s3.eu-west-1.amazonaws.com/cdr-faker-data-dfad0cb7/cdr_2025-08-02.parquet/d1de776ed6f747c688e0280773b470d5.snappy.parquet\n'
          '  query:     209850\n'
          '  location:  dory_util.cpp:1776\n'
          '  process:   worker_thread [pid=16259]\n'
          '  -----------------------------------------------\n',
 'HasResultSet': False,
 'Id': '701b1514-9f49-4101-9736-61a1ca94bbff',
 'QueryString': '\n'
                '                    COPY public.cdr_records \n'
                '                    FROM '
                "'s3://cdr-faker-data-dfad0cb7/cdr_2025-08-02.parquet/'\n"
                '                    credentials\n'
                "                    ''\n"
                '                    \n'
                '                    FORMAT AS PARQUET;\n'
                '        ',
 'RedshiftPid': 1073930392,
 'RedshiftQueryId': 209851,
 'ResponseMetadata': {'HTTPHeaders': {'content-length': '1156',
                                      'content-type': 'application/x-amz-json-1.1',
                                      'date': 'Sat, 02 Aug 2025 04:07:20 GMT',
                                      'x-amzn-requestid': 'a3dbd868-f4a1-4519-ae45-8d8569b665ef'},
                      'HTTPStatusCode': 200,
                      'RequestId': 'a3dbd868-f4a1-4519-ae45-8d8569b665ef',
                      'RetryAttempts': 0},
 'ResultRows': -1,
 'ResultSize': -1,
 'Status': 'FAILED',
 'UpdatedAt': datetime.datetime(2025, 8, 2, 4, 7, 10, 995000, tzinfo=tzlocal())}; 3498)
[2025-08-02T04:07:20.742+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-08-02T04:07:20.768+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
