[2025-08-01T12:41:10.881+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=cdr_pipeline/run_id=manual__2025-08-01T12:40:39.691074+00:00/task_id=load_to_redshift permission to 509
[2025-08-01T12:41:10.965+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=cdr_pipeline/run_id=manual__2025-08-01T12:40:39.691074+00:00/task_id=load_to_redshift permission to 509
[2025-08-01T12:41:11.014+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cdr_pipeline.load_to_redshift manual__2025-08-01T12:40:39.691074+00:00 [queued]>
[2025-08-01T12:41:11.031+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cdr_pipeline.load_to_redshift manual__2025-08-01T12:40:39.691074+00:00 [queued]>
[2025-08-01T12:41:11.033+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-08-01T12:41:11.073+0000] {taskinstance.py:2191} INFO - Executing <Task(S3ToRedshiftOperator): load_to_redshift> on 2025-08-01 12:40:39.691074+00:00
[2025-08-01T12:41:11.089+0000] {standard_task_runner.py:60} INFO - Started process 112 to run task
[2025-08-01T12:41:11.097+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'cdr_pipeline', 'load_to_redshift', 'manual__2025-08-01T12:40:39.691074+00:00', '--job-id', '117', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp2h1wtz6k']
[2025-08-01T12:41:11.100+0000] {standard_task_runner.py:88} INFO - Job 117: Subtask load_to_redshift
[2025-08-01T12:41:11.184+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=cdr_pipeline/run_id=manual__2025-08-01T12:40:39.691074+00:00/task_id=load_to_redshift permission to 509
[2025-08-01T12:41:11.203+0000] {task_command.py:423} INFO - Running <TaskInstance: cdr_pipeline.load_to_redshift manual__2025-08-01T12:40:39.691074+00:00 [running]> on host 481a36bbdf5a
[2025-08-01T12:41:11.378+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cdr_pipeline' AIRFLOW_CTX_TASK_ID='load_to_redshift' AIRFLOW_CTX_EXECUTION_DATE='2025-08-01T12:40:39.691074+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-01T12:40:39.691074+00:00'
[2025-08-01T12:41:11.417+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/transfers/s3_to_redshift.py", line 144, in execute
    conn = S3Hook.get_connection(conn_id=self.aws_conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/base.py", line 82, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 479, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `aws_default` isn't defined
[2025-08-01T12:41:11.423+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=cdr_pipeline, task_id=load_to_redshift, execution_date=20250801T124039, start_date=20250801T124111, end_date=20250801T124111
[2025-08-01T12:41:11.463+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 117 for task load_to_redshift (The conn_id `aws_default` isn't defined; 112)
[2025-08-01T12:41:11.512+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-08-01T12:41:11.554+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
