[2025-08-02T02:49:28.217+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=cdr_pipeline/run_id=manual__2025-08-02T02:49:12.586308+00:00/task_id=load_to_redshift permission to 509
[2025-08-02T02:49:28.308+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=cdr_pipeline/run_id=manual__2025-08-02T02:49:12.586308+00:00/task_id=load_to_redshift permission to 509
[2025-08-02T02:49:28.388+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cdr_pipeline.load_to_redshift manual__2025-08-02T02:49:12.586308+00:00 [queued]>
[2025-08-02T02:49:28.413+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cdr_pipeline.load_to_redshift manual__2025-08-02T02:49:12.586308+00:00 [queued]>
[2025-08-02T02:49:28.414+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-08-02T02:49:28.445+0000] {taskinstance.py:2191} INFO - Executing <Task(S3ToRedshiftOperator): load_to_redshift> on 2025-08-02 02:49:12.586308+00:00
[2025-08-02T02:49:28.467+0000] {standard_task_runner.py:60} INFO - Started process 2363 to run task
[2025-08-02T02:49:28.477+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'cdr_pipeline', 'load_to_redshift', 'manual__2025-08-02T02:49:12.586308+00:00', '--job-id', '107', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp32e5mint']
[2025-08-02T02:49:28.488+0000] {standard_task_runner.py:88} INFO - Job 107: Subtask load_to_redshift
[2025-08-02T02:49:28.608+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=cdr_pipeline/run_id=manual__2025-08-02T02:49:12.586308+00:00/task_id=load_to_redshift permission to 509
[2025-08-02T02:49:28.630+0000] {task_command.py:423} INFO - Running <TaskInstance: cdr_pipeline.load_to_redshift manual__2025-08-02T02:49:12.586308+00:00 [running]> on host f2527419f673
[2025-08-02T02:49:28.826+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cdr_pipeline' AIRFLOW_CTX_TASK_ID='load_to_redshift' AIRFLOW_CTX_EXECUTION_DATE='2025-08-02T02:49:12.586308+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-02T02:49:12.586308+00:00'
[2025-08-02T02:49:28.847+0000] {base.py:83} INFO - Using connection ID 'aws_default' for task execution.
[2025-08-02T02:49:28.861+0000] {base.py:83} INFO - Using connection ID 'aws_default' for task execution.
[2025-08-02T02:49:28.863+0000] {connection_wrapper.py:378} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2025-08-02T02:49:28.888+0000] {s3_to_redshift.py:192} INFO - Executing COPY command...
[2025-08-02T02:49:28.899+0000] {base.py:83} INFO - Using connection ID 'redshift_default' for task execution.
[2025-08-02T02:49:28.902+0000] {connection_wrapper.py:378} INFO - AWS Connection (conn_id='redshift_default', conn_type='aws') credentials retrieved from login and password.
[2025-08-02T02:49:28.904+0000] {warnings.py:109} WARNING - <string>:9: AirflowProviderDeprecationWarning: Host tf-redshift-cluster.ci896s3qzt6h.eu-west-1.redshift.amazonaws.com:5439/dev_db specified in the connection is not used. Please, set it on extra['endpoint_url'] instead

[2025-08-02T02:49:31.255+0000] {redshift_data.py:113} INFO - Polling statement ce882077-250d-43a8-b967-07c1967065a9
[2025-08-02T02:49:31.442+0000] {redshift_data.py:129} INFO - Query STARTED
[2025-08-02T02:49:41.453+0000] {redshift_data.py:113} INFO - Polling statement ce882077-250d-43a8-b967-07c1967065a9
[2025-08-02T02:49:41.777+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/transfers/s3_to_redshift.py", line 194, in execute
    redshift_hook.execute_query(sql=sql, **self.redshift_data_api_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/redshift_data.py", line 107, in execute_query
    self.wait_for_results(statement_id, poll_interval=poll_interval)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/redshift_data.py", line 124, in wait_for_results
    raise ValueError(
ValueError: Statement 'ce882077-250d-43a8-b967-07c1967065a9' terminated with status FAILED. Response details: {'ClusterIdentifier': 'tf-redshift-cluster',
 'CreatedAt': datetime.datetime(2025, 8, 2, 2, 49, 30, 989000, tzinfo=tzlocal()),
 'Database': 'dev_db',
 'DbUser': 'masterdb',
 'Duration': -1,
 'Error': 'ERROR: Spectrum Scan Error\n'
          '  Detail: \n'
          '  -----------------------------------------------\n'
          '  error:  Spectrum Scan Error\n'
          '  code:      15007\n'
          '  context:   File '
          "'https://s3.eu-west-1.amazonaws.com/cdr-faker-data-dfad0cb7/cdr_2025-08-02.parquet/5ab9379766d44b69948e2285b09e4854.snappy.parquet' "
          'has an incompatible Parquet schema for column '
          "'s3://cdr-faker-data-dfad0cb7/cdr_2025-08-02.parquet.call_start'. "
          'Column \n'
          '  query:     208538\n'
          '  location:  dory_util.cpp:1776\n'
          '  process:   worker_thread [pid=13839]\n'
          '  -----------------------------------------------\n',
 'HasResultSet': False,
 'Id': 'ce882077-250d-43a8-b967-07c1967065a9',
 'QueryString': '\n'
                '                    COPY public.cdr_records \n'
                '                    FROM '
                "'s3://cdr-faker-data-dfad0cb7/cdr_2025-08-02.parquet'\n"
                '                    credentials\n'
                "                    ''\n"
                '                    \n'
                '                    FORMAT AS PARQUET;\n'
                '        ',
 'RedshiftPid': 1073840269,
 'RedshiftQueryId': 208539,
 'ResponseMetadata': {'HTTPHeaders': {'content-length': '1183',
                                      'content-type': 'application/x-amz-json-1.1',
                                      'date': 'Sat, 02 Aug 2025 02:49:41 GMT',
                                      'x-amzn-requestid': '7c1e999c-5f37-46e2-ac2d-019aad134727'},
                      'HTTPStatusCode': 200,
                      'RequestId': '7c1e999c-5f37-46e2-ac2d-019aad134727',
                      'RetryAttempts': 0},
 'ResultRows': -1,
 'ResultSize': -1,
 'Status': 'FAILED',
 'UpdatedAt': datetime.datetime(2025, 8, 2, 2, 49, 31, 917000, tzinfo=tzlocal())}
[2025-08-02T02:49:41.798+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=cdr_pipeline, task_id=load_to_redshift, execution_date=20250802T024912, start_date=20250802T024928, end_date=20250802T024941
[2025-08-02T02:49:41.823+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 107 for task load_to_redshift (Statement 'ce882077-250d-43a8-b967-07c1967065a9' terminated with status FAILED. Response details: {'ClusterIdentifier': 'tf-redshift-cluster',
 'CreatedAt': datetime.datetime(2025, 8, 2, 2, 49, 30, 989000, tzinfo=tzlocal()),
 'Database': 'dev_db',
 'DbUser': 'masterdb',
 'Duration': -1,
 'Error': 'ERROR: Spectrum Scan Error\n'
          '  Detail: \n'
          '  -----------------------------------------------\n'
          '  error:  Spectrum Scan Error\n'
          '  code:      15007\n'
          '  context:   File '
          "'https://s3.eu-west-1.amazonaws.com/cdr-faker-data-dfad0cb7/cdr_2025-08-02.parquet/5ab9379766d44b69948e2285b09e4854.snappy.parquet' "
          'has an incompatible Parquet schema for column '
          "'s3://cdr-faker-data-dfad0cb7/cdr_2025-08-02.parquet.call_start'. "
          'Column \n'
          '  query:     208538\n'
          '  location:  dory_util.cpp:1776\n'
          '  process:   worker_thread [pid=13839]\n'
          '  -----------------------------------------------\n',
 'HasResultSet': False,
 'Id': 'ce882077-250d-43a8-b967-07c1967065a9',
 'QueryString': '\n'
                '                    COPY public.cdr_records \n'
                '                    FROM '
                "'s3://cdr-faker-data-dfad0cb7/cdr_2025-08-02.parquet'\n"
                '                    credentials\n'
                "                    ''\n"
                '                    \n'
                '                    FORMAT AS PARQUET;\n'
                '        ',
 'RedshiftPid': 1073840269,
 'RedshiftQueryId': 208539,
 'ResponseMetadata': {'HTTPHeaders': {'content-length': '1183',
                                      'content-type': 'application/x-amz-json-1.1',
                                      'date': 'Sat, 02 Aug 2025 02:49:41 GMT',
                                      'x-amzn-requestid': '7c1e999c-5f37-46e2-ac2d-019aad134727'},
                      'HTTPStatusCode': 200,
                      'RequestId': '7c1e999c-5f37-46e2-ac2d-019aad134727',
                      'RetryAttempts': 0},
 'ResultRows': -1,
 'ResultSize': -1,
 'Status': 'FAILED',
 'UpdatedAt': datetime.datetime(2025, 8, 2, 2, 49, 31, 917000, tzinfo=tzlocal())}; 2363)
[2025-08-02T02:49:41.875+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-08-02T02:49:41.897+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
