[2025-08-02T02:54:45.767+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=cdr_pipeline/run_id=manual__2025-08-02T02:49:12.586308+00:00/task_id=load_to_redshift permission to 509
[2025-08-02T02:54:45.829+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=cdr_pipeline/run_id=manual__2025-08-02T02:49:12.586308+00:00/task_id=load_to_redshift permission to 509
[2025-08-02T02:54:45.881+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cdr_pipeline.load_to_redshift manual__2025-08-02T02:49:12.586308+00:00 [queued]>
[2025-08-02T02:54:45.896+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cdr_pipeline.load_to_redshift manual__2025-08-02T02:49:12.586308+00:00 [queued]>
[2025-08-02T02:54:45.897+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2025-08-02T02:54:45.916+0000] {taskinstance.py:2191} INFO - Executing <Task(S3ToRedshiftOperator): load_to_redshift> on 2025-08-02 02:49:12.586308+00:00
[2025-08-02T02:54:45.927+0000] {standard_task_runner.py:60} INFO - Started process 2443 to run task
[2025-08-02T02:54:45.934+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'cdr_pipeline', 'load_to_redshift', 'manual__2025-08-02T02:49:12.586308+00:00', '--job-id', '111', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpb6u1k7_e']
[2025-08-02T02:54:45.936+0000] {standard_task_runner.py:88} INFO - Job 111: Subtask load_to_redshift
[2025-08-02T02:54:46.013+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=cdr_pipeline/run_id=manual__2025-08-02T02:49:12.586308+00:00/task_id=load_to_redshift permission to 509
[2025-08-02T02:54:46.029+0000] {task_command.py:423} INFO - Running <TaskInstance: cdr_pipeline.load_to_redshift manual__2025-08-02T02:49:12.586308+00:00 [running]> on host f2527419f673
[2025-08-02T02:54:46.205+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cdr_pipeline' AIRFLOW_CTX_TASK_ID='load_to_redshift' AIRFLOW_CTX_EXECUTION_DATE='2025-08-02T02:49:12.586308+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-02T02:49:12.586308+00:00'
[2025-08-02T02:54:46.227+0000] {base.py:83} INFO - Using connection ID 'aws_default' for task execution.
[2025-08-02T02:54:46.241+0000] {base.py:83} INFO - Using connection ID 'aws_default' for task execution.
[2025-08-02T02:54:46.242+0000] {connection_wrapper.py:378} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2025-08-02T02:54:46.268+0000] {s3_to_redshift.py:192} INFO - Executing COPY command...
[2025-08-02T02:54:46.279+0000] {base.py:83} INFO - Using connection ID 'redshift_default' for task execution.
[2025-08-02T02:54:46.280+0000] {connection_wrapper.py:378} INFO - AWS Connection (conn_id='redshift_default', conn_type='aws') credentials retrieved from login and password.
[2025-08-02T02:54:46.281+0000] {warnings.py:109} WARNING - <string>:9: AirflowProviderDeprecationWarning: Host tf-redshift-cluster.ci896s3qzt6h.eu-west-1.redshift.amazonaws.com:5439/dev_db specified in the connection is not used. Please, set it on extra['endpoint_url'] instead

[2025-08-02T02:54:48.219+0000] {redshift_data.py:113} INFO - Polling statement a86b8140-8664-4eb4-a70d-aa8f9c9c4a37
[2025-08-02T02:54:48.407+0000] {redshift_data.py:129} INFO - Query STARTED
[2025-08-02T02:54:58.449+0000] {redshift_data.py:113} INFO - Polling statement a86b8140-8664-4eb4-a70d-aa8f9c9c4a37
[2025-08-02T02:54:58.729+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/transfers/s3_to_redshift.py", line 194, in execute
    redshift_hook.execute_query(sql=sql, **self.redshift_data_api_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/redshift_data.py", line 107, in execute_query
    self.wait_for_results(statement_id, poll_interval=poll_interval)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/redshift_data.py", line 124, in wait_for_results
    raise ValueError(
ValueError: Statement 'a86b8140-8664-4eb4-a70d-aa8f9c9c4a37' terminated with status FAILED. Response details: {'ClusterIdentifier': 'tf-redshift-cluster',
 'CreatedAt': datetime.datetime(2025, 8, 2, 2, 54, 48, 313000, tzinfo=tzlocal()),
 'Database': 'dev_db',
 'DbUser': 'masterdb',
 'Duration': -1,
 'Error': 'ERROR: Spectrum Scan Error\n'
          '  Detail: \n'
          '  -----------------------------------------------\n'
          '  error:  Spectrum Scan Error\n'
          '  code:      15007\n'
          '  context:   File '
          "'https://s3.eu-west-1.amazonaws.com/cdr-faker-data-dfad0cb7/cdr_2025-08-02.parquet/3bb9bc59257844b3ad3bcb79e4a1a1d4.snappy.parquet' "
          'has an incompatible Parquet schema for column '
          "'s3://cdr-faker-data-dfad0cb7/cdr_2025-08-02.parquet.call_start'. "
          'Column \n'
          '  query:     208609\n'
          '  location:  dory_util.cpp:1776\n'
          '  process:   worker_thread [pid=19998]\n'
          '  -----------------------------------------------\n',
 'HasResultSet': False,
 'Id': 'a86b8140-8664-4eb4-a70d-aa8f9c9c4a37',
 'QueryString': '\n'
                '                    COPY public.cdr_records \n'
                '                    FROM '
                "'s3://cdr-faker-data-dfad0cb7/cdr_2025-08-02.parquet'\n"
                '                    credentials\n'
                "                    ''\n"
                '                    \n'
                '                    FORMAT AS PARQUET;\n'
                '        ',
 'RedshiftPid': 1073823873,
 'RedshiftQueryId': 208610,
 'ResponseMetadata': {'HTTPHeaders': {'content-length': '1183',
                                      'content-type': 'application/x-amz-json-1.1',
                                      'date': 'Sat, 02 Aug 2025 02:54:59 GMT',
                                      'x-amzn-requestid': 'c295702b-cadb-4a9e-9097-5da14e5d6409'},
                      'HTTPStatusCode': 200,
                      'RequestId': 'c295702b-cadb-4a9e-9097-5da14e5d6409',
                      'RetryAttempts': 0},
 'ResultRows': -1,
 'ResultSize': -1,
 'Status': 'FAILED',
 'UpdatedAt': datetime.datetime(2025, 8, 2, 2, 54, 49, 246000, tzinfo=tzlocal())}
[2025-08-02T02:54:58.747+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=cdr_pipeline, task_id=load_to_redshift, execution_date=20250802T024912, start_date=20250802T025445, end_date=20250802T025458
[2025-08-02T02:54:58.770+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 111 for task load_to_redshift (Statement 'a86b8140-8664-4eb4-a70d-aa8f9c9c4a37' terminated with status FAILED. Response details: {'ClusterIdentifier': 'tf-redshift-cluster',
 'CreatedAt': datetime.datetime(2025, 8, 2, 2, 54, 48, 313000, tzinfo=tzlocal()),
 'Database': 'dev_db',
 'DbUser': 'masterdb',
 'Duration': -1,
 'Error': 'ERROR: Spectrum Scan Error\n'
          '  Detail: \n'
          '  -----------------------------------------------\n'
          '  error:  Spectrum Scan Error\n'
          '  code:      15007\n'
          '  context:   File '
          "'https://s3.eu-west-1.amazonaws.com/cdr-faker-data-dfad0cb7/cdr_2025-08-02.parquet/3bb9bc59257844b3ad3bcb79e4a1a1d4.snappy.parquet' "
          'has an incompatible Parquet schema for column '
          "'s3://cdr-faker-data-dfad0cb7/cdr_2025-08-02.parquet.call_start'. "
          'Column \n'
          '  query:     208609\n'
          '  location:  dory_util.cpp:1776\n'
          '  process:   worker_thread [pid=19998]\n'
          '  -----------------------------------------------\n',
 'HasResultSet': False,
 'Id': 'a86b8140-8664-4eb4-a70d-aa8f9c9c4a37',
 'QueryString': '\n'
                '                    COPY public.cdr_records \n'
                '                    FROM '
                "'s3://cdr-faker-data-dfad0cb7/cdr_2025-08-02.parquet'\n"
                '                    credentials\n'
                "                    ''\n"
                '                    \n'
                '                    FORMAT AS PARQUET;\n'
                '        ',
 'RedshiftPid': 1073823873,
 'RedshiftQueryId': 208610,
 'ResponseMetadata': {'HTTPHeaders': {'content-length': '1183',
                                      'content-type': 'application/x-amz-json-1.1',
                                      'date': 'Sat, 02 Aug 2025 02:54:59 GMT',
                                      'x-amzn-requestid': 'c295702b-cadb-4a9e-9097-5da14e5d6409'},
                      'HTTPStatusCode': 200,
                      'RequestId': 'c295702b-cadb-4a9e-9097-5da14e5d6409',
                      'RetryAttempts': 0},
 'ResultRows': -1,
 'ResultSize': -1,
 'Status': 'FAILED',
 'UpdatedAt': datetime.datetime(2025, 8, 2, 2, 54, 49, 246000, tzinfo=tzlocal())}; 2443)
[2025-08-02T02:54:58.821+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-08-02T02:54:58.854+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
