[2025-08-02T03:13:32.377+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=cdr_pipeline/run_id=manual__2025-08-02T02:53:13.538457+00:00/task_id=load_to_redshift permission to 509
[2025-08-02T03:13:32.480+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=cdr_pipeline/run_id=manual__2025-08-02T02:53:13.538457+00:00/task_id=load_to_redshift permission to 509
[2025-08-02T03:13:32.572+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cdr_pipeline.load_to_redshift manual__2025-08-02T02:53:13.538457+00:00 [queued]>
[2025-08-02T03:13:32.615+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cdr_pipeline.load_to_redshift manual__2025-08-02T02:53:13.538457+00:00 [queued]>
[2025-08-02T03:13:32.618+0000] {taskinstance.py:2170} INFO - Starting attempt 9 of 10
[2025-08-02T03:13:32.685+0000] {taskinstance.py:2191} INFO - Executing <Task(S3ToRedshiftOperator): load_to_redshift> on 2025-08-02 02:53:13.538457+00:00
[2025-08-02T03:13:32.715+0000] {standard_task_runner.py:60} INFO - Started process 2720 to run task
[2025-08-02T03:13:32.732+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'cdr_pipeline', 'load_to_redshift', 'manual__2025-08-02T02:53:13.538457+00:00', '--job-id', '119', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpx1wo8zge']
[2025-08-02T03:13:32.743+0000] {standard_task_runner.py:88} INFO - Job 119: Subtask load_to_redshift
[2025-08-02T03:13:32.860+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=cdr_pipeline/run_id=manual__2025-08-02T02:53:13.538457+00:00/task_id=load_to_redshift permission to 509
[2025-08-02T03:13:32.883+0000] {task_command.py:423} INFO - Running <TaskInstance: cdr_pipeline.load_to_redshift manual__2025-08-02T02:53:13.538457+00:00 [running]> on host f2527419f673
[2025-08-02T03:13:33.120+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cdr_pipeline' AIRFLOW_CTX_TASK_ID='load_to_redshift' AIRFLOW_CTX_EXECUTION_DATE='2025-08-02T02:53:13.538457+00:00' AIRFLOW_CTX_TRY_NUMBER='9' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-02T02:53:13.538457+00:00'
[2025-08-02T03:13:33.139+0000] {base.py:83} INFO - Using connection ID 'aws_default' for task execution.
[2025-08-02T03:13:33.161+0000] {base.py:83} INFO - Using connection ID 'aws_default' for task execution.
[2025-08-02T03:13:33.163+0000] {connection_wrapper.py:378} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2025-08-02T03:13:33.197+0000] {s3_to_redshift.py:192} INFO - Executing COPY command...
[2025-08-02T03:13:33.217+0000] {base.py:83} INFO - Using connection ID 'redshift_default' for task execution.
[2025-08-02T03:13:33.219+0000] {connection_wrapper.py:378} INFO - AWS Connection (conn_id='redshift_default', conn_type='aws') credentials retrieved from login and password.
[2025-08-02T03:13:33.222+0000] {warnings.py:109} WARNING - <string>:9: AirflowProviderDeprecationWarning: Host tf-redshift-cluster.ci896s3qzt6h.eu-west-1.redshift.amazonaws.com:5439/dev_db specified in the connection is not used. Please, set it on extra['endpoint_url'] instead

[2025-08-02T03:13:36.010+0000] {redshift_data.py:113} INFO - Polling statement d149ef0e-cf0a-4f05-9e39-bea9e89a0c96
[2025-08-02T03:13:36.196+0000] {redshift_data.py:129} INFO - Query STARTED
[2025-08-02T03:13:46.208+0000] {redshift_data.py:113} INFO - Polling statement d149ef0e-cf0a-4f05-9e39-bea9e89a0c96
[2025-08-02T03:13:46.439+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/transfers/s3_to_redshift.py", line 194, in execute
    redshift_hook.execute_query(sql=sql, **self.redshift_data_api_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/redshift_data.py", line 107, in execute_query
    self.wait_for_results(statement_id, poll_interval=poll_interval)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/redshift_data.py", line 124, in wait_for_results
    raise ValueError(
ValueError: Statement 'd149ef0e-cf0a-4f05-9e39-bea9e89a0c96' terminated with status FAILED. Response details: {'ClusterIdentifier': 'tf-redshift-cluster',
 'CreatedAt': datetime.datetime(2025, 8, 2, 3, 13, 35, 773000, tzinfo=tzlocal()),
 'Database': 'dev_db',
 'DbUser': 'masterdb',
 'Duration': -1,
 'Error': 'ERROR: Spectrum Scan Error\n'
          '  Detail: \n'
          '  -----------------------------------------------\n'
          '  error:  Spectrum Scan Error\n'
          '  code:      15007\n'
          '  context:   File '
          "'https://s3.eu-west-1.amazonaws.com/cdr-faker-data-dfad0cb7/cdr_2025-08-02.parquet/0ef3d4a1e2e247ecb5c289ae13397c0d.snappy.parquet' "
          'has an incompatible Parquet schema for column '
          "'s3://cdr-faker-data-dfad0cb7/cdr_2025-08-02.parquet.call_start'. "
          'Column \n'
          '  query:     208884\n'
          '  location:  dory_util.cpp:1776\n'
          '  process:   worker_thread [pid=27135]\n'
          '  -----------------------------------------------\n',
 'HasResultSet': False,
 'Id': 'd149ef0e-cf0a-4f05-9e39-bea9e89a0c96',
 'QueryString': '\n'
                '                    COPY public.cdr_records \n'
                '                    FROM '
                "'s3://cdr-faker-data-dfad0cb7/cdr_2025-08-02.parquet'\n"
                '                    credentials\n'
                "                    ''\n"
                '                    \n'
                '                    FORMAT AS PARQUET;\n'
                '        ',
 'RedshiftPid': 1073766559,
 'RedshiftQueryId': 208885,
 'ResponseMetadata': {'HTTPHeaders': {'content-length': '1183',
                                      'content-type': 'application/x-amz-json-1.1',
                                      'date': 'Sat, 02 Aug 2025 03:13:46 GMT',
                                      'x-amzn-requestid': '18010e2f-55c9-4589-aee7-914e017d0f43'},
                      'HTTPStatusCode': 200,
                      'RequestId': '18010e2f-55c9-4589-aee7-914e017d0f43',
                      'RetryAttempts': 0},
 'ResultRows': -1,
 'ResultSize': -1,
 'Status': 'FAILED',
 'UpdatedAt': datetime.datetime(2025, 8, 2, 3, 13, 36, 702000, tzinfo=tzlocal())}
[2025-08-02T03:13:46.458+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=cdr_pipeline, task_id=load_to_redshift, execution_date=20250802T025313, start_date=20250802T031332, end_date=20250802T031346
[2025-08-02T03:13:46.486+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 119 for task load_to_redshift (Statement 'd149ef0e-cf0a-4f05-9e39-bea9e89a0c96' terminated with status FAILED. Response details: {'ClusterIdentifier': 'tf-redshift-cluster',
 'CreatedAt': datetime.datetime(2025, 8, 2, 3, 13, 35, 773000, tzinfo=tzlocal()),
 'Database': 'dev_db',
 'DbUser': 'masterdb',
 'Duration': -1,
 'Error': 'ERROR: Spectrum Scan Error\n'
          '  Detail: \n'
          '  -----------------------------------------------\n'
          '  error:  Spectrum Scan Error\n'
          '  code:      15007\n'
          '  context:   File '
          "'https://s3.eu-west-1.amazonaws.com/cdr-faker-data-dfad0cb7/cdr_2025-08-02.parquet/0ef3d4a1e2e247ecb5c289ae13397c0d.snappy.parquet' "
          'has an incompatible Parquet schema for column '
          "'s3://cdr-faker-data-dfad0cb7/cdr_2025-08-02.parquet.call_start'. "
          'Column \n'
          '  query:     208884\n'
          '  location:  dory_util.cpp:1776\n'
          '  process:   worker_thread [pid=27135]\n'
          '  -----------------------------------------------\n',
 'HasResultSet': False,
 'Id': 'd149ef0e-cf0a-4f05-9e39-bea9e89a0c96',
 'QueryString': '\n'
                '                    COPY public.cdr_records \n'
                '                    FROM '
                "'s3://cdr-faker-data-dfad0cb7/cdr_2025-08-02.parquet'\n"
                '                    credentials\n'
                "                    ''\n"
                '                    \n'
                '                    FORMAT AS PARQUET;\n'
                '        ',
 'RedshiftPid': 1073766559,
 'RedshiftQueryId': 208885,
 'ResponseMetadata': {'HTTPHeaders': {'content-length': '1183',
                                      'content-type': 'application/x-amz-json-1.1',
                                      'date': 'Sat, 02 Aug 2025 03:13:46 GMT',
                                      'x-amzn-requestid': '18010e2f-55c9-4589-aee7-914e017d0f43'},
                      'HTTPStatusCode': 200,
                      'RequestId': '18010e2f-55c9-4589-aee7-914e017d0f43',
                      'RetryAttempts': 0},
 'ResultRows': -1,
 'ResultSize': -1,
 'Status': 'FAILED',
 'UpdatedAt': datetime.datetime(2025, 8, 2, 3, 13, 36, 702000, tzinfo=tzlocal())}; 2720)
[2025-08-02T03:13:46.535+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-08-02T03:13:46.558+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
