[2025-08-02T18:21:29.432+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=cdr_pipeline/run_id=manual__2025-08-02T04:05:53.026388+00:00/task_id=load_to_redshift permission to 509
[2025-08-02T18:21:29.511+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=cdr_pipeline/run_id=manual__2025-08-02T04:05:53.026388+00:00/task_id=load_to_redshift permission to 509
[2025-08-02T18:21:29.562+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cdr_pipeline.load_to_redshift manual__2025-08-02T04:05:53.026388+00:00 [queued]>
[2025-08-02T18:21:29.579+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cdr_pipeline.load_to_redshift manual__2025-08-02T04:05:53.026388+00:00 [queued]>
[2025-08-02T18:21:29.580+0000] {taskinstance.py:2170} INFO - Starting attempt 18 of 19
[2025-08-02T18:21:29.601+0000] {taskinstance.py:2191} INFO - Executing <Task(S3ToRedshiftOperator): load_to_redshift> on 2025-08-02 04:05:53.026388+00:00
[2025-08-02T18:21:29.612+0000] {standard_task_runner.py:60} INFO - Started process 491 to run task
[2025-08-02T18:21:29.620+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'cdr_pipeline', 'load_to_redshift', 'manual__2025-08-02T04:05:53.026388+00:00', '--job-id', '180', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpvurfkbza']
[2025-08-02T18:21:29.623+0000] {standard_task_runner.py:88} INFO - Job 180: Subtask load_to_redshift
[2025-08-02T18:21:29.721+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=cdr_pipeline/run_id=manual__2025-08-02T04:05:53.026388+00:00/task_id=load_to_redshift permission to 509
[2025-08-02T18:21:29.740+0000] {task_command.py:423} INFO - Running <TaskInstance: cdr_pipeline.load_to_redshift manual__2025-08-02T04:05:53.026388+00:00 [running]> on host 2f861e5e7e42
[2025-08-02T18:21:29.927+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cdr_pipeline' AIRFLOW_CTX_TASK_ID='load_to_redshift' AIRFLOW_CTX_EXECUTION_DATE='2025-08-02T04:05:53.026388+00:00' AIRFLOW_CTX_TRY_NUMBER='18' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-02T04:05:53.026388+00:00'
[2025-08-02T18:21:29.945+0000] {base.py:83} INFO - Using connection ID 'aws_default' for task execution.
[2025-08-02T18:21:29.959+0000] {base.py:83} INFO - Using connection ID 'aws_default' for task execution.
[2025-08-02T18:21:29.962+0000] {connection_wrapper.py:378} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2025-08-02T18:21:29.979+0000] {s3_to_redshift.py:192} INFO - Executing COPY command...
[2025-08-02T18:21:29.991+0000] {base.py:83} INFO - Using connection ID 'redshift_default' for task execution.
[2025-08-02T18:21:29.994+0000] {connection_wrapper.py:378} INFO - AWS Connection (conn_id='redshift_default', conn_type='aws') credentials retrieved from login and password.
[2025-08-02T18:21:29.995+0000] {warnings.py:109} WARNING - <string>:9: AirflowProviderDeprecationWarning: Host tf-redshift-cluster.ci896s3qzt6h.eu-west-1.redshift.amazonaws.com:5439/dev_db specified in the connection is not used. Please, set it on extra['endpoint_url'] instead

[2025-08-02T18:21:33.399+0000] {redshift_data.py:113} INFO - Polling statement 8093fd25-048d-47f5-ba00-6bd4d1ddf34c
[2025-08-02T18:21:33.640+0000] {redshift_data.py:129} INFO - Query STARTED
[2025-08-02T18:21:43.648+0000] {redshift_data.py:113} INFO - Polling statement 8093fd25-048d-47f5-ba00-6bd4d1ddf34c
[2025-08-02T18:21:43.955+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/transfers/s3_to_redshift.py", line 194, in execute
    redshift_hook.execute_query(sql=sql, **self.redshift_data_api_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/redshift_data.py", line 107, in execute_query
    self.wait_for_results(statement_id, poll_interval=poll_interval)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/redshift_data.py", line 124, in wait_for_results
    raise ValueError(
ValueError: Statement '8093fd25-048d-47f5-ba00-6bd4d1ddf34c' terminated with status FAILED. Response details: {'ClusterIdentifier': 'tf-redshift-cluster',
 'CreatedAt': datetime.datetime(2025, 8, 2, 18, 21, 33, 174000, tzinfo=tzlocal()),
 'Database': 'dev_db',
 'DbUser': 'masterdb',
 'Duration': -1,
 'Error': 'ERROR: Spectrum Scan Error\n'
          '  Detail: \n'
          '  -----------------------------------------------\n'
          '  error:  Spectrum Scan Error\n'
          '  code:      15007\n'
          '  context:   File '
          "'https://s3.eu-west-1.amazonaws.com/cdr-faker-data-dfad0cb7/cdr_2025-08-02.parquet/ffda064dc84849d08a001688fab83ca4.snappy.parquet' "
          'has an incompatible Parquet schema for column '
          "'s3://cdr-faker-data-dfad0cb7/cdr_2025-08-02.parquet/.call_quality'. "
          'Colu\n'
          '  query:     3764\n'
          '  location:  dory_util.cpp:1776\n'
          '  process:   worker_thread [pid=29582]\n'
          '  -----------------------------------------------\n',
 'HasResultSet': False,
 'Id': '8093fd25-048d-47f5-ba00-6bd4d1ddf34c',
 'QueryString': '\n'
                '                    COPY public.cdr_records \n'
                '                    FROM '
                "'s3://cdr-faker-data-dfad0cb7/cdr_2025-08-02.parquet/'\n"
                '                    credentials\n'
                "                    ''\n"
                '                    \n'
                '                    FORMAT AS PARQUET;\n'
                '        ',
 'RedshiftPid': 1073979537,
 'RedshiftQueryId': 3765,
 'ResponseMetadata': {'HTTPHeaders': {'content-length': '1180',
                                      'content-type': 'application/x-amz-json-1.1',
                                      'date': 'Sat, 02 Aug 2025 18:21:43 GMT',
                                      'x-amzn-requestid': 'c5699f87-9efb-474f-be7d-9beb49afccec'},
                      'HTTPStatusCode': 200,
                      'RequestId': 'c5699f87-9efb-474f-be7d-9beb49afccec',
                      'RetryAttempts': 0},
 'ResultRows': -1,
 'ResultSize': -1,
 'Status': 'FAILED',
 'UpdatedAt': datetime.datetime(2025, 8, 2, 18, 21, 42, 826000, tzinfo=tzlocal())}
[2025-08-02T18:21:43.985+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=cdr_pipeline, task_id=load_to_redshift, execution_date=20250802T040553, start_date=20250802T182129, end_date=20250802T182143
[2025-08-02T18:21:44.010+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 180 for task load_to_redshift (Statement '8093fd25-048d-47f5-ba00-6bd4d1ddf34c' terminated with status FAILED. Response details: {'ClusterIdentifier': 'tf-redshift-cluster',
 'CreatedAt': datetime.datetime(2025, 8, 2, 18, 21, 33, 174000, tzinfo=tzlocal()),
 'Database': 'dev_db',
 'DbUser': 'masterdb',
 'Duration': -1,
 'Error': 'ERROR: Spectrum Scan Error\n'
          '  Detail: \n'
          '  -----------------------------------------------\n'
          '  error:  Spectrum Scan Error\n'
          '  code:      15007\n'
          '  context:   File '
          "'https://s3.eu-west-1.amazonaws.com/cdr-faker-data-dfad0cb7/cdr_2025-08-02.parquet/ffda064dc84849d08a001688fab83ca4.snappy.parquet' "
          'has an incompatible Parquet schema for column '
          "'s3://cdr-faker-data-dfad0cb7/cdr_2025-08-02.parquet/.call_quality'. "
          'Colu\n'
          '  query:     3764\n'
          '  location:  dory_util.cpp:1776\n'
          '  process:   worker_thread [pid=29582]\n'
          '  -----------------------------------------------\n',
 'HasResultSet': False,
 'Id': '8093fd25-048d-47f5-ba00-6bd4d1ddf34c',
 'QueryString': '\n'
                '                    COPY public.cdr_records \n'
                '                    FROM '
                "'s3://cdr-faker-data-dfad0cb7/cdr_2025-08-02.parquet/'\n"
                '                    credentials\n'
                "                    ''\n"
                '                    \n'
                '                    FORMAT AS PARQUET;\n'
                '        ',
 'RedshiftPid': 1073979537,
 'RedshiftQueryId': 3765,
 'ResponseMetadata': {'HTTPHeaders': {'content-length': '1180',
                                      'content-type': 'application/x-amz-json-1.1',
                                      'date': 'Sat, 02 Aug 2025 18:21:43 GMT',
                                      'x-amzn-requestid': 'c5699f87-9efb-474f-be7d-9beb49afccec'},
                      'HTTPStatusCode': 200,
                      'RequestId': 'c5699f87-9efb-474f-be7d-9beb49afccec',
                      'RetryAttempts': 0},
 'ResultRows': -1,
 'ResultSize': -1,
 'Status': 'FAILED',
 'UpdatedAt': datetime.datetime(2025, 8, 2, 18, 21, 42, 826000, tzinfo=tzlocal())}; 491)
[2025-08-02T18:21:44.058+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-08-02T18:21:44.085+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
